// Golden diff-test: for each fixture case, run TS patchBuffer on input.jsonl
// with the old/new from meta.json, and assert byte-identity (via sha256)
// with the Python mvp.py-generated expected.jsonl.
//
// Fixtures are generated by scripts/generate-golden-patch.py. If mvp.py's
// regex is ever changed (unlikely — 2026-04-19 was the last fix), regenerate
// all fixtures in one commit so the drift is reviewable.

import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  autoFixDotQuote,
  patchBuffer,
} from '../../../src/core/project-move/jsonl-patch.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURE_ROOT = join(
  __dirname,
  '..',
  '..',
  'fixtures',
  'project-move',
  'golden',
);

interface Meta {
  old: string;
  new: string;
  autoFixDotQuote?: boolean;
}

function listCases(): string[] {
  return readdirSync(FIXTURE_ROOT).filter((name) => {
    try {
      return statSync(join(FIXTURE_ROOT, name)).isDirectory();
    } catch {
      return false;
    }
  });
}

function sha256(buf: Buffer): string {
  return createHash('sha256').update(buf).digest('hex');
}

describe('jsonl-patch golden diff-test (TS vs Python mvp.py byte parity)', () => {
  const cases = listCases();
  if (cases.length === 0) {
    it.skip('no golden fixtures found — run scripts/generate-golden-patch.py', () => {});
    return;
  }

  for (const caseName of cases) {
    it(`${caseName} produces byte-identical output`, () => {
      const dir = join(FIXTURE_ROOT, caseName);
      const input = readFileSync(join(dir, 'input.jsonl'));
      const meta = JSON.parse(
        readFileSync(join(dir, 'meta.json'), 'utf8'),
      ) as Meta;
      const expectedSha = readFileSync(
        join(dir, 'expected.sha256'),
        'utf8',
      ).trim();
      const expectedBytes = readFileSync(join(dir, 'expected.jsonl'));

      // Apply mvp.py's two-stage semantics in the same order:
      //   1. patch_file (regex w/ terminator lookahead)
      //   2. auto_fix_dot_quote (optional)
      let { buffer } = patchBuffer(input, meta.old, meta.new);
      if (meta.autoFixDotQuote) {
        buffer = autoFixDotQuote(buffer, meta.old, meta.new).buffer;
      }

      const actualSha = sha256(buffer);

      // Give a helpful failure message on byte mismatch — show the first diff.
      if (actualSha !== expectedSha) {
        const maxLen = Math.min(buffer.length, expectedBytes.length);
        let firstDiff = -1;
        for (let i = 0; i < maxLen; i++) {
          if (buffer[i] !== expectedBytes[i]) {
            firstDiff = i;
            break;
          }
        }
        throw new Error(
          [
            `Byte mismatch in ${caseName}:`,
            `  expected sha256: ${expectedSha}`,
            `  actual   sha256: ${actualSha}`,
            `  expected bytes: ${expectedBytes.length}, actual: ${buffer.length}`,
            firstDiff >= 0
              ? `  first differing byte at offset ${firstDiff}: expected ${expectedBytes[firstDiff]}, actual ${buffer[firstDiff]}`
              : '  (sizes differ but no byte difference in common prefix)',
            '  actual output head (first 200 bytes):',
            `  ${JSON.stringify(buffer.subarray(0, 200).toString('utf8'))}`,
          ].join('\n'),
        );
      }

      expect(actualSha).toBe(expectedSha);
    });
  }
});
