import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, relative, resolve } from 'node:path';
import { CodexAdapter } from '../src/adapters/codex.js';
import { Database } from '../src/core/db.js';
import { Indexer } from '../src/core/indexer.js';

const repoRoot = resolve(import.meta.dirname, '..');

function parseArgs(argv = process.argv.slice(2)): { out: string } {
  const outIndex = argv.indexOf('--out');
  return {
    out:
      outIndex >= 0
        ? resolve(argv[outIndex + 1])
        : join(repoRoot, 'tests/fixtures/indexer-parity'),
  };
}

function gitCommit(): string {
  try {
    return execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return 'unknown';
  }
}

function sortJson(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortJson);
  if (!value || typeof value !== 'object') return value;
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(value).sort()) {
    out[key] = sortJson((value as Record<string, unknown>)[key]);
  }
  return out;
}

function stableJson(value: unknown): string {
  return `${JSON.stringify(sortJson(value), null, 2)}\n`;
}

function normalizeValue(value: unknown): unknown {
  if (typeof value === 'string') return value.split(repoRoot).join('<repo>');
  return value;
}

function sha256(value: unknown): string {
  return createHash('sha256').update(stableJson(value)).digest('hex');
}

function normalizeRows(
  rows: Record<string, unknown>[],
): Record<string, unknown>[] {
  return rows
    .map((row) => {
      const copy = { ...row };
      for (const key of [
        'indexed_at',
        'created_at',
        'computed_at',
        'updated_at',
        'last_indexed',
        'link_checked_at',
      ]) {
        if (key in copy) copy[key] = '<volatile>';
      }
      for (const [key, value] of Object.entries(copy)) {
        copy[key] = normalizeValue(value);
      }
      return copy;
    })
    .sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b)));
}

function tableChecksum(
  db: Database,
  table: string,
  orderBy: string,
): { count: number; sha256: string; rows: Record<string, unknown>[] } {
  const rows = normalizeRows(
    db
      .getRawDb()
      .prepare(`SELECT * FROM ${table} ORDER BY ${orderBy}`)
      .all() as Record<string, unknown>[],
  );
  return { count: rows.length, sha256: sha256(rows), rows };
}

function selectedMetadata(db: Database): Record<string, string> {
  const rows = db
    .getRawDb()
    .prepare(
      "SELECT key, value FROM metadata WHERE key IN ('schema_version', 'fts_version') ORDER BY key",
    )
    .all() as { key: string; value: string }[];
  return Object.fromEntries(rows.map((row) => [row.key, row.value]));
}

export async function generateIndexerParityFixtures(
  out: string,
): Promise<void> {
  rmSync(out, { recursive: true, force: true });
  const fixtureRoot = join(out, 'fixture-root');
  const codexRoot = join(fixtureRoot, 'codex');
  mkdirSync(join(codexRoot, '2026/01/15'), { recursive: true });
  copyFileSync(
    join(repoRoot, 'tests/fixtures/codex/sample.jsonl'),
    join(codexRoot, '2026/01/15/rollout-sample.jsonl'),
  );
  mkdirSync(join(out, 'parent-detection'), { recursive: true });
  mkdirSync(join(out, 'startup-backfills'), { recursive: true });
  writeFileSync(
    join(out, 'parent-detection/README.md'),
    'Generated by scripts/gen-indexer-parity-fixtures.ts for Stage 2 parent-link parity expansion.\n',
  );
  writeFileSync(
    join(out, 'startup-backfills/README.md'),
    'Generated by scripts/gen-indexer-parity-fixtures.ts for Stage 2 startup backfill parity expansion.\n',
  );

  const tmp = mkdtempSync(join(tmpdir(), 'engram-indexer-parity-'));
  const dbPath = join(tmp, 'indexer.sqlite');
  const db = new Database(dbPath);
  try {
    const adapter = new CodexAdapter(codexRoot);
    const indexer = new Indexer(db, [adapter], {
      authoritativeNode: 'fixture-node',
    });
    const indexedCount = await indexer.indexAll();
    const output = {
      schemaVersion: 1,
      sourceCommit: gitCommit(),
      indexedCount,
      fixtureRoot: 'tests/fixtures/indexer-parity/fixture-root',
      tables: {
        sessions: tableChecksum(db, 'sessions', 'id'),
        session_costs: tableChecksum(db, 'session_costs', 'session_id, model'),
        session_tools: tableChecksum(
          db,
          'session_tools',
          'session_id, tool_name',
        ),
        session_files: tableChecksum(
          db,
          'session_files',
          'session_id, file_path, action',
        ),
        session_index_jobs: tableChecksum(db, 'session_index_jobs', 'id'),
        metadata: {
          count: Object.keys(selectedMetadata(db)).length,
          sha256: sha256(selectedMetadata(db)),
          rows: selectedMetadata(db),
        },
      },
      parentLinkColumns: {
        rows: db
          .getRawDb()
          .prepare(
            'SELECT id, parent_session_id, suggested_parent_id, link_source FROM sessions ORDER BY id',
          )
          .all(),
      },
    };
    writeFileSync(join(out, 'expected-db-checksums.json'), stableJson(output));
  } finally {
    db.close();
    rmSync(tmp, { recursive: true, force: true });
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { out } = parseArgs();
  await generateIndexerParityFixtures(out);
  console.log(`indexer parity fixture generated: ${relative(repoRoot, out)}`);
}
