import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const repoRoot = resolve(import.meta.dirname, '../..');
const generatorSource = readFileSync(
  resolve(repoRoot, 'scripts/gen-mcp-contract-fixtures.ts'),
  'utf8',
);

describe('MCP contract fixture generator', () => {
  it('derives MCP tool metadata from the Swift registry instead of the deleted TypeScript entrypoint', () => {
    expect(generatorSource).toContain(
      'macos/EngramMCP/Core/MCPToolRegistry.swift',
    );
    expect(generatorSource).not.toContain("resolve(repoRoot, 'src/index.ts')");
    expect(generatorSource).not.toContain('extractToolNamesFromIndex');
    expect(generatorSource).not.toContain('extractInitializeResultFromIndex');
  });

  it('keeps Swift executable goldens outside the generated fixture ownership boundary', () => {
    expect(generatorSource).not.toContain('rmSync(goldenDir');
    expect(generatorSource).not.toMatch(/from '\.\.\/src\/tools\//);
    expect(generatorSource).not.toContain('const goldens:');
  });

  it('deduplicates tool names extracted from the Swift registry', () => {
    expect(generatorSource).toContain('return [...new Set(toolNames)]');
  });

  it('vacuums the fixture DB before close so regenerated bytes stay stable (repro)', () => {
    // CI runs `git diff --exit-code` on tests/fixtures/mcp-contract.sqlite.
    // Without VACUUM, SQLite page layout can differ across regenerations even
    // when logical table content is identical, flapping macOS fixture gates.
    expect(generatorSource).toMatch(/raw\.exec\(\s*['"]VACUUM['"]\s*\)/);
  });
});
